package com.misael.escuelabd;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class NewAlumnoGUI extends JFrame {

    private JPanel     panelCards;
    private JPanel     panelInfoAlumno;
    private JPanel     panelInfoTutor;
    private JPanel     panelInfoGrado;
    private JLabel     labelTitulo;
    private JTextField tfTelefonoAlumno;
    private JTextField tfNombreAlumno;
    private JComboBox  tfGenero;
    private JLabel     labelNombre;
    private JLabel     labelGenero;
    private JLabel     labelTelefono;
    private JPanel     panelMain;
    private JLabel     labelAnterior;
    private JLabel     labelSiguiente;
    private JTextField tfNombreTutor;
    private JTextField tfRFCTutor;
    private JTextField tfTelefonoTutor;
    private JLabel labelNombreTutor;
    private JLabel labelRFC;
    private JLabel labelTelefonoTutor;

    NewAlumnoGUI() {
        this.setSize(500, 700);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setContentPane(panelMain);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void initActionListeners() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        panelCards = new JPanel();
        panelCards.setLayout(new CardLayout(0, 0));
        panelMain.add(panelCards, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelInfoAlumno = new JPanel();
        panelInfoAlumno.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelCards.add(panelInfoAlumno, "Card1");
        labelTitulo = new JLabel();
        labelTitulo.setText("Registro nuevo alumno");
        panelInfoAlumno.add(labelTitulo, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNombre = new JLabel();
        labelNombre.setText("Nombre:");
        panelInfoAlumno.add(labelNombre, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelGenero = new JLabel();
        labelGenero.setText("Género:");
        panelInfoAlumno.add(labelGenero, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfTelefonoAlumno = new JTextField();
        panelInfoAlumno.add(tfTelefonoAlumno, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelTelefono = new JLabel();
        labelTelefono.setText("Teléfono:");
        panelInfoAlumno.add(labelTelefono, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNombreAlumno = new JTextField();
        panelInfoAlumno.add(tfNombreAlumno, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfGenero = new JComboBox();
        panelInfoAlumno.add(tfGenero, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelInfoTutor = new JPanel();
        panelInfoTutor.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelCards.add(panelInfoTutor, "Card2");
        labelNombreTutor = new JLabel();
        labelNombreTutor.setText("Nombre:");
        panelInfoTutor.add(labelNombreTutor, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNombreTutor = new JTextField();
        panelInfoTutor.add(tfNombreTutor, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelTelefonoTutor = new JLabel();
        labelTelefonoTutor.setText("Teléfono:");
        panelInfoTutor.add(labelTelefonoTutor, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfTelefonoTutor = new JTextField();
        panelInfoTutor.add(tfTelefonoTutor, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfRFCTutor = new JTextField();
        panelInfoTutor.add(tfRFCTutor, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelRFC = new JLabel();
        labelRFC.setText("RFC:");
        panelInfoTutor.add(labelRFC, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelInfoGrado = new JPanel();
        panelInfoGrado.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelCards.add(panelInfoGrado, "Card3");
        labelAnterior = new JLabel();
        labelAnterior.setText("Anterior");
        panelMain.add(labelAnterior, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelSiguiente = new JLabel();
        labelSiguiente.setText("Siguiente");
        panelMain.add(labelSiguiente, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
