package PracticaDesktop;

import com.formdev.flatlaf.FlatLightLaf;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class Interfaz extends JFrame {

    JMenuBar  jMenuBar      = new JMenuBar();
    JMenu     jMenu         = new JMenu("Menú");
    JMenuItem menuVentana1  = new JMenuItem("Ventana 1");
    JMenuItem menuVentana2  = new JMenuItem("Ventana 2");
    JMenuItem menuItemSalir = new JMenuItem("Salir");
    private JPanel         panel1;
    private JDesktopPane   desktopPane;
    private JInternalFrame internalFrame;

    public static void main(String[] args) {
        FlatLightLaf.setup();
        var interfaz = new Interfaz();
    }

    public Interfaz() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setSize(640, 480);
        this.setLocationRelativeTo(null);
        $$$setupUI$$$();
        configurarComponentes();
        this.setJMenuBar(jMenuBar);
        this.setVisible(true);
    }

    public void configurarComponentes() {
        jMenu.add(menuVentana1);
        jMenu.add(menuVentana2);
        jMenu.addSeparator();
        jMenu.add(menuItemSalir);


        menuVentana1.addActionListener(e -> {
            desktopPane.add(internalFrame);
            internalFrame.setVisible(true);
        });

        jMenuBar.add(jMenu);

    }

    public void eventoBoton() {
        var    unHilo = new UnHilo();
        Thread hilo   = new Thread(unHilo);
        hilo.start();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
