import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.misael.Alumno;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.ArrayList;
import java.util.Objects;

public class AlumnoGUI extends JFrame {
    private JTextField tfNumControl;
    private JTextField tfNombre;
    private JTextField tfNumControlOut;
    private JTextField tfNombreOut;
    private JTextField tfSemestreOut;
    private JTextField tfEspecialidadOut;
    private JButton btnGuardar;
    private JButton btnMostrar;
    private JLabel labelNumControl;
    private JLabel labelNombre;
    private JLabel labelSemestre;
    private JLabel labelNumControlOut;
    private JLabel labelNombreOut;
    private JLabel labelSemestreOut;
    private JLabel labelEspecialidad;
    private JLabel labelEspecialidadOut;
    private JPanel panelPrincipal;

    String[] listaEspecialidades = {"Ing. Sistemas", "Ing. Mecánica", "Ing. Civil", "Ing. Arquitectura", "Ing. Administración", "Ing. Química"};
    String[] listaSemestres = {"1", "2", "3", "4", "5", "6", "7", "8", "9"};

    private JComboBox<String> cbEspecialidad;
    private JComboBox<String> cbSemestre;

    ArrayList<Alumno> listaAlumnos = new ArrayList<>();

    public AlumnoGUI(String title) {
        super(title);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setContentPane(panelPrincipal);
        this.pack();
        this.setResizable(false);
        configurarComponentes();
        initActionListeners();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(10, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        labelNumControl = new JLabel();
        labelNumControl.setText("Número de Control");
        panelPrincipal.add(labelNumControl, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNumControl = new JTextField();
        panelPrincipal.add(tfNumControl, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelNombre = new JLabel();
        labelNombre.setText("Nombre");
        panelPrincipal.add(labelNombre, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNombre = new JTextField();
        panelPrincipal.add(tfNombre, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelSemestre = new JLabel();
        labelSemestre.setText("Semestre");
        panelPrincipal.add(labelSemestre, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGuardar = new JButton();
        btnGuardar.setText("Guardar");
        panelPrincipal.add(btnGuardar, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNumControlOut = new JLabel();
        labelNumControlOut.setText("Número de Control");
        panelPrincipal.add(labelNumControlOut, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNombreOut = new JLabel();
        labelNombreOut.setText("Nombre");
        panelPrincipal.add(labelNombreOut, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelSemestreOut = new JLabel();
        labelSemestreOut.setText("Semestre");
        panelPrincipal.add(labelSemestreOut, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNumControlOut = new JTextField();
        tfNumControlOut.setEditable(false);
        panelPrincipal.add(tfNumControlOut, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfNombreOut = new JTextField();
        tfNombreOut.setEditable(false);
        panelPrincipal.add(tfNombreOut, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfSemestreOut = new JTextField();
        tfSemestreOut.setEditable(false);
        panelPrincipal.add(tfSemestreOut, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnMostrar = new JButton();
        btnMostrar.setText("Mostrar");
        panelPrincipal.add(btnMostrar, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelEspecialidad = new JLabel();
        labelEspecialidad.setText("Especialidad");
        panelPrincipal.add(labelEspecialidad, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelEspecialidadOut = new JLabel();
        labelEspecialidadOut.setText("Especialidad");
        panelPrincipal.add(labelEspecialidadOut, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfEspecialidadOut = new JTextField();
        tfEspecialidadOut.setEditable(false);
        panelPrincipal.add(tfEspecialidadOut, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cbEspecialidad = new JComboBox();
        panelPrincipal.add(cbEspecialidad, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbSemestre = new JComboBox();
        panelPrincipal.add(cbSemestre, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }

    public void configurarComponentes() {
        cbEspecialidad.setModel(new DefaultComboBoxModel<>(listaEspecialidades));
        cbSemestre.setModel(new DefaultComboBoxModel<>(listaSemestres));
    }

    public void initActionListeners() {
        btnGuardar.addActionListener(e -> {
            String numControl = tfNumControl.getText();
            String nombre = tfNombre.getText();
            String especialidad = Objects.requireNonNull(cbEspecialidad.getSelectedItem()).toString();
            String semestre = Objects.requireNonNull(cbSemestre.getSelectedItem()).toString();

            listaAlumnos.add(new Alumno(numControl, nombre, especialidad, semestre));

            JOptionPane.showMessageDialog(null, "Alumno registrado correctamente.");
        });

        btnMostrar.addActionListener(e -> {
            tfNumControlOut.setText(listaAlumnos.get(0).getNumControl());
            tfNombreOut.setText(listaAlumnos.get(0).getNombre());
            tfEspecialidadOut.setText(listaAlumnos.get(0).getEspecialidad());
            tfSemestreOut.setText(listaAlumnos.get(0).getSemestre());
        });
    }
}
