import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.lang.Math;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import java.awt.Dimension;
import java.awt.Insets;
import java.util.ArrayList;

import com.misael.Producto;
import com.misael.Cliente;

public class GUIProductoCliente extends JFrame {
    private JPanel     panelPrincipal;
    private JTextField tfNumSerie;
    private JTextField tfNombreProducto;
    private JTextField tfPrecio;
    private JLabel     labelProducto;
    private JLabel     labelNumSerie;
    private JLabel     labelPrecio;
    private JLabel     labelNombreProducto;
    private JTextField tfNumCuenta;
    private JTextField tfNombreCliente;
    private JTextField tfTelefono;
    private JTextArea  taInformacion;
    private JLabel     labelCliente;
    private JLabel     labelNumCuenta;
    private JLabel     labelNombreCliente;
    private JLabel     labelTelefono;
    private JPanel     PanelRegistros;
    private JPanel     panelCliente;
    private JPanel     panelProducto;
    private JPanel     panelInformacion;
    private JLabel     labelInformacion;
    private JButton    btnRegistrar;
    private JPanel     panelBoton;
    private JButton    btnAnterior;
    private JButton    btnSiguiente;

    ArrayList<Producto> listaProductos = new ArrayList<>();
    ArrayList<Cliente>  listaClientes  = new ArrayList<>();

    int currentProductoandCliente = 0;

    public GUIProductoCliente() {
        super("Interfaz Producto-Cliente");
        initActionListeners();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setContentPane(panelPrincipal);
        this.pack();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        listaClientes.add(new Cliente("4328432", "Juanito", "732473232849"));
        listaClientes.add(new Cliente("5443543", "Pepe", "32948723234"));
        listaClientes.add(new Cliente("9080909", "Martín", "73247353229"));
        listaProductos.add(new Producto("34298432", "Jabón", 23));
        listaProductos.add(new Producto("23478632", "Papel", 14));
        listaProductos.add(new Producto("3432432", "Cartón", 34));

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        PanelRegistros = new JPanel();
        PanelRegistros.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal.add(PanelRegistros, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelCliente = new JPanel();
        panelCliente.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        PanelRegistros.add(panelCliente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        labelCliente = new JLabel();
        labelCliente.setText("Cliente:");
        panelCliente.add(labelCliente, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNumCuenta = new JLabel();
        labelNumCuenta.setText("Número de cuenta:");
        panelCliente.add(labelNumCuenta, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNombreCliente = new JLabel();
        labelNombreCliente.setText("Nombre:");
        panelCliente.add(labelNombreCliente, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelTelefono = new JLabel();
        labelTelefono.setText("Teléfono:");
        panelCliente.add(labelTelefono, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNumCuenta = new JTextField();
        panelCliente.add(tfNumCuenta, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfNombreCliente = new JTextField();
        panelCliente.add(tfNombreCliente, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfTelefono = new JTextField();
        panelCliente.add(tfTelefono, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panelProducto = new JPanel();
        panelProducto.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        PanelRegistros.add(panelProducto, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        labelProducto = new JLabel();
        labelProducto.setText("Producto:");
        panelProducto.add(labelProducto, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNumSerie = new JLabel();
        labelNumSerie.setText("Número de serie:");
        panelProducto.add(labelNumSerie, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelPrecio = new JLabel();
        labelPrecio.setText("Precio:");
        panelProducto.add(labelPrecio, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNombreProducto = new JLabel();
        labelNombreProducto.setText("Nombre:");
        panelProducto.add(labelNombreProducto, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfNumSerie = new JTextField();
        panelProducto.add(tfNumSerie, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfNombreProducto = new JTextField();
        panelProducto.add(tfNombreProducto, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfPrecio = new JTextField();
        panelProducto.add(tfPrecio, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panelInformacion = new JPanel();
        panelInformacion.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal.add(panelInformacion, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelInformacion.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        taInformacion = new JTextArea();
        taInformacion.setLineWrap(false);
        panelInformacion.add(taInformacion, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(300, 200), new Dimension(150, 50), null, 1, false));
        labelInformacion = new JLabel();
        labelInformacion.setText("Información:");
        panelInformacion.add(labelInformacion, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelInformacion.add(panel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnAnterior = new JButton();
        btnAnterior.setText("<<<<");
        panel1.add(btnAnterior, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSiguiente = new JButton();
        btnSiguiente.setText(">>>>");
        panel1.add(btnSiguiente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelBoton = new JPanel();
        panelBoton.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal.add(panelBoton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelBoton.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnRegistrar = new JButton();
        btnRegistrar.setText("Registrar");
        panelBoton.add(btnRegistrar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }

    public void initActionListeners() {
        btnRegistrar.addActionListener(e -> {
            registrarProducto();
            registrarCliente();
            JOptionPane.showMessageDialog(null, "Registro realizado correctamente");
            clearTextFields();

            if (currentProductoandCliente == 0) {
                taInformacion.setText(getCurrentObjectText());
            }
        });

        btnAnterior.addActionListener(e -> {
            currentProductoandCliente--;
            taInformacion.setText(getCurrentObjectText());
        });

        btnSiguiente.addActionListener(e -> {
            currentProductoandCliente++;
            taInformacion.setText(getCurrentObjectText());
        });
    }

    private String getCurrentObjectText() {
        String resultado = "";
        if (currentProductoandCliente >= 0 && currentProductoandCliente < listaClientes.size()) {
            resultado += "\nNombre del cliente: " + listaClientes.get(currentProductoandCliente).getNombre();
            resultado += "\nNúmero de cliente: " + listaClientes.get(currentProductoandCliente).getNumCliente();
            resultado += "\nTeléfono: " + listaClientes.get(currentProductoandCliente).getTelefono();
            resultado += "\nNúmero de serie del producto: " + listaProductos.get(currentProductoandCliente).getNumSerie();
            resultado += "\nNombre del producto: " + listaProductos.get(currentProductoandCliente).getNombre();
            resultado += "\nPrecio: $" + listaProductos.get(currentProductoandCliente).getPrecio();
        }
        return resultado;
    }

    private void registrarProducto() {
        String numSerie       = tfNumSerie.getText();
        String nombreProducto = tfNombreProducto.getText();
        float  precio         = Float.parseFloat(tfPrecio.getText());

        listaProductos.add(new Producto(numSerie, nombreProducto, precio));
    }

    private void registrarCliente() {
        String numCuenta     = tfNumCuenta.getText();
        String nombreCliente = tfNombreCliente.getText();
        String telefono      = tfTelefono.getText();

        listaClientes.add(new Cliente(numCuenta, nombreCliente, telefono));
    }

    public void clearTextFields() {
        tfNumSerie.setText("");
        tfNombreProducto.setText("");
        tfPrecio.setText("");
        tfNumCuenta.setText("");
        tfNombreCliente.setText("");
        tfTelefono.setText("");
    }

    public static void main(String[] args) {
        FlatDarkLaf.setup();
        new GUIProductoCliente();
    }

}
