package com.misael.hilos;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class Interfaz extends JFrame {
    private JPanel  panelPrincipal;
    private JLabel  labelFireStatus;
    private JButton btnToggleFire;

    public Interfaz() {
        this.setSize(640, 480);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setContentPane(panelPrincipal);
        configurarComponentes();
        initActionListeners();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    private void configurarComponentes() {
    }

    private void initActionListeners() {

        Alarma alarma = new Alarma();
        Thread hilo   = new Thread(alarma);
        hilo.start();

        btnToggleFire.addActionListener(e -> {
            Alarma.isOnFire = !Alarma.isOnFire;
            labelFireStatus.setText(String.valueOf(Alarma.isOnFire));
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        labelFireStatus = new JLabel();
        labelFireStatus.setText("Label");
        panelPrincipal.add(labelFireStatus, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnToggleFire = new JButton();
        btnToggleFire.setText("Toggle fire");
        panelPrincipal.add(btnToggleFire, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }

}
